#version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "MiCluster"
      CASSANDRA_DC: "DC1"
      CASSANDRA_RACK: "RAC1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - cassandra-net

volumes:
  cassandradata:

networks:
  cassandra-net:
